### ISSUE TITLE
Implement nginx on docker deployment to access the dutluk frontend without a port number

### ISSUE THREAD

**Issue by hdenizdogan** [enshkn/BOUN-SWE-574-Fall-23-G2#210]
A reverse proxy from 3000 to port 80 might be beneficial. This way we can access the frontend like `http://1.2.3.4 `instead of `http://1.2.3.4:3000` . docker-compose.yml has to be edited and a new file called nginx.conf have to be generated on the same directory of the said .yml file.

expected docker-compose.yml content:

```
version: '3.7'

services:
  backend:
    build:
      context: ./dutluk_backend
    container_name: dutluk-backend
    image: hdenizdogan/dutluk-backend:latest
    ports:
      - "8080:8080"
    env_file:
      - ./dutluk_frontend/.env
    depends_on:
      - db
    volumes:
      - backend-data:/path/to/backend/data
    restart: always

  frontend:
    build:
      context: ./dutluk_frontend
    container_name: dutluk-frontend
    image: hdenizdogan/dutluk-frontend:latest
    ports:
      - "3000:3000"
    env_file:
      - ./dutluk_frontend/.env
    depends_on:
      - backend
    restart: always

  nginx:
    image: nginx:latest
    container_name: dutluk-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  db:
    image: postgres
    restart: always
    container_name: db
    ports:
      - "5432:5432"
    env_file:
      - ./dutluk_frontend/.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  backend-data:
  db-data:
```
 and the nginx.conf content that has to be on the same directory 
```
events {}

http {
    server {
        listen 80;

        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
```
